#!/usr/bin/env bash

export FANTASYBROS__POSTGRES_USER=${FANTASYBROS__POSTGRES_USER}
export FANTASYBROS__POSTGRES_PASSWORD=${FANTASYBROS__POSTGRES_PASSWORD}
export FANTASYBROS__POSTGRES_HOST=${FANTASYBROS__POSTGRES_HOST}
export FANTASYBROS__POSTGRES_PORT=${FANTASYBROS__POSTGRES_PORT}
export FANTASYBROS__POSTGRES_DB=${FANTASYBROS__POSTGRES_DB}
export AIRFLOW_POSTGRES_USER=${AIRFLOW_POSTGRES_USER}
export AIRFLOW_POSTGRES_PASSWORD=${AIRFLOW_POSTGRES_PASSWORD}
export AIRFLOW_POSTGRES_HOST=${AIRFLOW_POSTGRES_HOST}
export AIRFLOW_POSTGRES_PORT=${AIRFLOW_POSTGRES_PORT}
export AIRFLOW_POSTGRES_DB=${AIRFLOW_POSTGRES_DB}
export AIRFLOW_EMAIL=${AIRFLOW_EMAIL}
export AIRFLOW_UID=${AIRFLOW_UID}
export AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
export AWS_SECRET_KEY=${AWS_SECRET_KEY}
export AWS_BUCKET=${AWS_BUCKET}


# Update airflow db connection string
AIRFLOW__DATABASE__SQL_ALCHEMY_CONN="postgresql+psycopg2://${AIRFLOW_POSTGRES_USER}:${AIRFLOW_POSTGRES_PASSWORD}@${AIRFLOW_POSTGRES_HOST}:${AIRFLOW_POSTGRES_PORT}/${AIRFLOW_POSTGRES_DB}"
export AIRFLOW__DATABASE__SQL_ALCHEMY_CONN


# Initialize airflow db and migrate to Postgres
airflow db migrate

# Create airflow user
airflow users create \
   --username ${AIRFLOW_POSTGRES_USER} \
   --password ${AIRFLOW_POSTGRES_PASSWORD} \
   --firstname airflow \
   --lastname airflow \
   --role Admin \
   --email ${AIRFLOW_EMAIL}

# Kick off airflow scheduler and webserver services
airflow scheduler &

airflow webserver