---
version: '3'
x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  command: server --console-address ":9090" /data
  ports:
    - "9000:9000"
    - "9090:9090"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3


services:
  postgres-ff-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${AIRFLOW__CONN__POSTGRES_LOCAL_USER}
      - POSTGRES_PASSWORD=${AIRFLOW__CONN__POSTGRES_LOCAL_PASSWORD}
      - POSTGRES_DB=${AIRFLOW__CONN__POSTGRES_LOCAL_DB}
    volumes:
      - postgres-ff-db-volume:/var/lib/postgresql/data
      - ./airflow/config/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
      test: ["CMD", "pg_isready -U ${AIRFLOW__CONN__POSTGRES_LOCAL_USER} -d ${AIRFLOW__CONN__POSTGRES_LOCAL_DB}"]
      interval: 5s
      retries: 5
    ports:
      - "5431:5432"
    restart: always
  
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${AIRFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_POSTGRES_DB}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

  minio:
    <<: *minio-common
    hostname: minio1
    environment:
      - MINIO_ROOT_USER=${AIRFLOW__CONN__MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${AIRFLOW__CONN__MINIO_ROOT_PASSWORD}
    volumes:
      - /minio/data:/data
    restart: always

  pgadmin4:
      image: dpage/pgadmin4
      restart: always
      environment:
          - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
          - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
      ports:
          - "15432:80"

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    command: webserver
    container_name: webserver
    ports:
      - 8008:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8008/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres


volumes:
  postgres-db-volume:
  postgres-ff-db-volume: