fantasyBrosDbt:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('AIRFLOW__CONN__POSTGRES_LOCAL_HOST') }}"
      user: "{{ env_var('AIRFLOW__CONN__POSTGRES_LOCAL_USER') }}"
      password: "{{ env_var('AIRFLOW__CONN__POSTGRES_LOCAL_PASSWORD') }}"
      port: "{{ env_var('AIRFLOW__CONN__POSTGRES_LOCAL_PORT') | as_number }}"
      dbname: "{{ env_var('AIRFLOW__CONN__POSTGRES_LOCAL_DB') }}"
      schema: staging
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections
      search_path:
      role:
      sslmode:

  target: dev
