name: CI
on: [push]
jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: Build docker image and spin up container
        run: |
          docker build -t fantasybros-airflow .
          docker run --entrypoint bash  --name fantasybros-ci fantasybros-airflow
      
      - name: Run formatters and linter
        run: |
          isort .
          python -m black -S --line-length 79 .
          flake8 --extend-ignore=E501,W605 /opt/airflow

      - name: Run tests
        run: pytest -p no:warnings
